### ISSUE TITLE
Glitching effect for a webpage using the Web Page Widget

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/widget-web-page#39] opened 2015-12-09 00:37 UTC
**Steps:**
Add a company website page to the Web Page Widget and upon distributing to a live Display, a glitch (ie element flickering, white areas on the presentation) occurs.  See https://rva.risevision.com/#/PRESENTATION_MANAGE/id=37647072-7c29-4340-8e34-515da0652b2a?cid=960b72df-9af7-476b-8a47-b67ded4c779d

As a test, I created a new presentation and added an alternative website page in the Web Page Widget (https://rva.risevision.com/#/PRESENTATION_MANAGE/id=eb512755-4c3f-4177-9bb5-074308dbdf00?cid=960b72df-9af7-476b-8a47-b67ded4c779d no glitches occur.

**Workarounds**
What I have done so far:
- I've repeated the same process but using the HTML Widget and then HTML Item and embedding the website as an iframe.  The same effect still occurs with the user website glitching and another website (ie RiseVision, etc) not glitching.  I think the issue may just be on the user website end, similar to certain sites not displaying iframes, but unlike the iframe block I couldn't tell via Console.
- I've scaled down the original presentation and deleted out other elements (ie other HTML Widgets, third party etc) believing that outside code may be corrupting the presentation but a glitch still occurs

**Tested on:**
Windows 7 using latest Stable release of Chrome 
Both RisePlayerPackagedApp 15.11.20.7944 and Windows RisePlayer 2015.10.12.15.11

**How it should work:**
No glitches to occur for the user website.

**Comment by lapinnoir** [comment] 2015-12-09 00:37
Intercom conversation https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/1513189601

**Comment by lapinnoir** [comment] 2015-12-09 17:22
FYI: Current workaround is to do a gif png screencast of the website interactive/animated elements.

**Comment by robb-price** [comment] 2015-12-21 15:07
@lapinnoir Do we know what it is about the website that is causing it to glitch? That is the info we need to give to the Apps team, instead of having them trying to figure it out. Can we determine that?

**Comment by lapinnoir** [comment] 2015-12-21 15:34
@robb-price When I looked into the site's source code, I couldn't locate what the problem is in their website that would cause the glitch.

**Comment by robb-price** [comment] 2015-12-21 16:49
@lapinnoir We can't give a bug to the Apps guys that sends them on a wild goose chase, we need to be clear with where the issue is. Has anyone else reported this issue? Would the user having the issue have any idea as to what scripts or code may be causing the issue on the page?

**Comment by lapinnoir** [comment] 2015-12-22 01:25
@robb-price This was isolated to their website.  When I did checks on other sites (risevision, w3c) this does not come up.  
The user reporting won't know what scripts/code is causing the issue, so I've recommended that they check with their web admin (see reply from Dec 8 https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1513189601) on what changes were done to the website.  
Otherwise I don't know why a certain website on the Web Page Widget would cause a glitch and why adding another website link wouldn't cause the glitch.  Would close the issue and attribute it to isolated/issue within user website?

**Comment by robb-price** [comment] 2015-12-22 16:40
@lapinnoir Yes, at this time, until someone else has a similar issue and we can determine the cause, let's just close it. Hopefully they can get some useful information back from their Network Admin, and that will give us more to test and report to the Apps team.

**Closed by robb-price** 2015-12-22 16:40 UTC
Labels: bug
