### ISSUE TITLE
Widget-web-page not reloading page after refresh

### ISSUE THREAD

**Issue by sgcweb** [Rise-Vision/widget-web-page#90] opened 2018-07-21 04:25 UTC
Presentations that were working last week now do not refresh web pages anymore.
the urls are
https://www.seatoskygondola.com  (for the weather and time sidebar)
https://www.seatoskygondola.com/challenge/results#/tv/  For the results table.
Attached ar pics of the screen before and after refresh.

![img_20180720_2127193](https://user-images.githubusercontent.com/25909870/43032108-d0f596c8-8c63-11e8-9697-db118fad14d1.jpg)

![img_20180720_2121000](https://user-images.githubusercontent.com/25909870/43032070-143db8f8-8c63-11e8-8780-721b96f7ac3b.jpg)

**Comment by santiagonoguez** [comment] 2018-07-23 13:47
Hi there !

Last week we did some changes to our cache busting strategy for refreshed pages, and that may be getting in the way for your pages being correctly displayed.

I'm currently working on settings that let disable those changes on displays that may be affected by those changes, like this seems to be the case. I'll keep you posted here.

Thanks !

**Comment by robb-price** [comment] 2018-07-23 13:47
Hi there!

Can I ask you to email support@risevision.com with some additional details regarding this? Specifically, a link to the Presentation you are using this webpage in?

This will help us a lot in determining what the issue may be here.

Thanks!

**Comment by sheadarlison** [comment] 2018-07-23 13:53
Hi @sgcweb,

Thanks for reporting this, we're aware of the issue and we're aiming to push a fix for this by tomorrow. 

As a workaround in the meantime could you please try removing the refresh and seeing if your web page works.

Thanks,
Shea

**Comment by santiagonoguez** [comment] 2018-07-23 19:57
Hi there again !

A new version of the web-page-widget has now been released. I tested it with both URLs that you provided above and they work fine for me now.

A new option called 'Enable cache buster ( recommended )' now appears in the Widget Settings for the web-page-widget when a refresh rate option is selected. For your presentation to run without problems, you should uncheck this option ( that is, disable the cache buster ), and then save and publish your presentation.

![capture](https://user-images.githubusercontent.com/33162690/43099609-4fab7624-8e88-11e8-8b49-b47410297678.png)

If you have trouble finding the 'Enable cache buster' option, you may need to delete your browser cache and/or restart your browser.

Please let us know if this solves the problem also in your presentation.

Thanks !

FYI @sheadarlison @robb-price

**Comment by santiagonoguez** [comment] 2018-07-24 13:53
Confirmed as fixed here:

https://help.risevision.com/hc/en-us/community/posts/360017707963-2-displays-not-showing-web-content

I'm closing this issue.

**Closed by santiagonoguez** 2018-07-24 13:53 UTC
